
import { GoogleGenAI, Type, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  console.error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

const parseBase64 = (base64String: string) => {
  const [header, data] = base64String.split(',');
  if (!header || !data) {
    throw new Error('Invalid base64 string format');
  }
  const mimeType = header.match(/:(.*?);/)?.[1] ?? 'image/png';
  return { data, mimeType };
}

export const generateCaptions = async (base64ImageWithPrefix: string): Promise<string[]> => {
  try {
    const { data, mimeType } = parseBase64(base64ImageWithPrefix);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType,
              data,
            },
          },
          {
            text: 'Analyze this image and generate 5 funny, viral-style meme captions. The captions should be short and punchy. Your response must be a valid JSON array of strings and nothing else.',
          },
        ],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.STRING
          }
        },
      }
    });
    
    const jsonStr = response.text.trim();
    const captions = JSON.parse(jsonStr);
    return captions;
  } catch (error) {
    console.error("Error generating captions:", error);
    throw new Error("Failed to generate captions. Please try again.");
  }
};

export const editImage = async (base64ImageWithPrefix: string, prompt: string): Promise<string> => {
  try {
    const { data, mimeType } = parseBase64(base64ImageWithPrefix);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data,
              mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });
    
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        const newMimeType: string = part.inlineData.mimeType;
        return `data:${newMimeType};base64,${base64ImageBytes}`;
      }
    }

    throw new Error("No image was generated by the model.");
  } catch (error) {
    console.error("Error editing image:", error);
    throw new Error("Failed to edit the image. The model may not have been able to fulfill the request.");
  }
};
